{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "voujr.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "voujr.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "voujr.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
{{- end }}
